name: Make Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: true
        type: string

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set project version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version_number }}

      - name: Build with Maven
        run: mvn -B package

      - name: Rename JAR
        run: mv target/JMusicBot-*-All.jar JMusicBot-${{ github.event.inputs.version_number }}.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: JMusicBot-${{ github.event.inputs.version_number }}.jar
          if-no-files-found: error

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_jar
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: .

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version_number }}
          name: Version ${{ github.event.inputs.version_number }}
          draft: true
          prerelease: false
          artifacts: "*.jar"
          body: |
            ${{ github.event.inputs.info }}

            ---
            ### Setup
            https://jmusicbot.com/setup
            https://jmusicbot.com/config

            # Download: [JMusicBot-${{ github.event.inputs.version_number }}.jar](https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.version_number }}/JMusicBot-${{ github.event.inputs.version_number }}.jar)
